---
title: "OUCRU-MORU bioinformatics workshop"
date: '`r format(Sys.time(), "%d %B, %Y")`'
                
---

# Introduction {-}

This is the website for the OUCRU-MORU bioinformatics workshop. 
This course is intended to take total beginners in bioinformatics and give them a grounding in the fundamentals. 
By the end of the 5 day course, participants should be able to work on the command line and run and interpret some fundamental bioinformatics software.

If you have any questions about this material, please contact pashton at oucru dot org or liz at tropmedres dot ac, or tweet us @flashton2003 & @embatty.

The data for the course is available [here](https://www.dropbox.com/sh/qd13lyrz21wwine/AADyOzVmRUAtQrhS5-AJjepqa?dl=0) (around 5GB).

# Course content {-}

**Day 1**

AM - Intro to genome sequencing, file formats and CLIMB, draw your career path

PM - Command line practical

**Day 2**

AM - Sequence quality control, speciation

11.30am - Break for OUCRU academic meeting

PM - Genome assembly

**Day 3**

AM - BLAST

11.30am - Break for OUCRU academic meeting - Prof Seemann

Post-lunch seminar - Trung Nguyen Vinh

PM - Annotation, visualisation, core/pan genome analysis

**Day 4**

AM - Alignment and variant calling

Post-lunch seminar - Hao Chung The

PM - Phylogenetics and outbreak investigation, viruses

**Day 5**

AM - Group presentations; you will be divided into teams and have to design a bioinformatics strategy to solve a specific microbiological question, and then present back to the whole group

12.30pm - OUCRU Academic meeting

PM - free time to talk to instructors about bioinformatics approaches to take with your own datasets or biological questions

# License {-}

This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).